import { QuestionnaireConfig, PatientConfig, TuringTestCase } from '@/types/questionnaire';

export const questionnaireConfig: QuestionnaireConfig = {
  version: '1.0.0',

  steps: [
    { id: 'profile', title: 'Profiel', description: 'Uw achtergrondinformatie' },
    { id: 'segmentation', title: 'Beoordeling segmentatie', description: 'Beoordeel segmentatiekwaliteit' },
    { id: 'feedback', title: 'Definitief indienen', description: 'Algehele ervaring en feedback' },
  ],

  profile_questions: [
    {
      id: 'experience',
      type: 'dropdown',
      label: 'Jaren ervaring als radiotherapeut (zonder AIOS jaren meegeteld)',
      required: true,
      placeholder: 'Selecteer uw ervaring...',
      choices: [
        { value: '0-2', label: '0-2 jaar' },
        { value: '3-5', label: '3-5 jaar' },
        { value: '6-10', label: '6-10 jaar' },
        { value: '10+', label: 'Meer dan 10 jaar' },
      ],
    },
    {
      id: 'ai_experience',
      type: 'dropdown',
      label: 'Uw ervaring met AI binnen de radiotherapie segmentaties',
      required: true,
      placeholder: 'Selecteer uw ervaring met AI...',
      choices: [
        { value: 'none', label: 'Geen ervaring' },
        { value: 'limited', label: 'Beperkte ervaring (bijv. tijdens opleiding of incidenteel gebruik)' },
        { value: 'moderate', label: 'Gemiddelde ervaring (bijv. regelmatig gebruik in de kliniek)' },
        { value: 'extensive', label: 'Veel ervaring (bijv. expertgebruiker of betrokken bij onderzoek/validatie)' },
      ],
    },
  ],

  segmentation_patients: [
    {
      patient_id: 'patient_01',
      display_name: 'Patient 01',
      variants: [
        {
          variant_id: 'A',
          case_id: 'patient_01_a',
          display_name: 'Versie A',
          questions: [
            {
              id: 'Q01_A_1',
              type: 'choice',
              label: '<p>CTVp_breast_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_2',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVp_breast_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_1', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_3',
              type: 'choice',
              label: '<p>CTVn_L1+L2_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_4',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L1+L2_A&nbsp;onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_3', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_5',
              type: 'choice',
              label: '<p>CTVn_L3+L4_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_6',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L3+L4_A&nbsp;onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_5', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_7',
              type: 'choice',
              label: '<p>CTVn_IMN_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_8',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_IMN_a onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_7', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_9',
              type: 'choice',
              label: '<p>Contra_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_10',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Contra_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_9', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_11',
              type: 'choice',
              label: '<p>Lungs_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_12',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Lungs_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_11', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_13',
              type: 'choice',
              label: '<p>Heart_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_14',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Heart_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_13', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_15',
              type: 'choice',
              label: '<p>Humeralhead_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_16',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Humeralhead_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_15', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_17',
              type: 'choice',
              label: '<p>Thyroid_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_18',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Thyroid_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_17', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_A_19',
              type: 'choice',
              label: '<p>Oesophagus_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_A_20',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Oesophagus_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_A_19', operator: 'equals', value: 'A003' },
            },
          ],
        },
        {
          variant_id: 'B',
          case_id: 'patient_01_b',
          display_name: 'Versie B',
          questions: [
            {
              id: 'Q01_B_1',
              type: 'choice',
              label: '<p>CTVp_breast_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_2',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVp_breast_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_1', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_3',
              type: 'choice',
              label: '<p>CTVn_L1+L2_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_4',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L1+L2_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_3', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_5',
              type: 'choice',
              label: '<p>CTVn_L3+L4_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_6',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L3+L4_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_5', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_7',
              type: 'choice',
              label: '<p>CTVn_IMN_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_8',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_IMN_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_7', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_9',
              type: 'choice',
              label: '<p>Contra_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_10',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Contra_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_9', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_11',
              type: 'choice',
              label: '<p>Lungs_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_12',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Lungs_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_11', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_13',
              type: 'choice',
              label: '<p>Heart_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_14',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Heart_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_13', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_15',
              type: 'choice',
              label: '<p>Humeralhead_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_16',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Humeralhead_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_15', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_17',
              type: 'choice',
              label: '<p>Thyroid_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_18',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Thyroid_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_17', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q01_B_19',
              type: 'choice',
              label: '<p>Oesophagus_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q01_B_20',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Oesophagus_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q01_B_19', operator: 'equals', value: 'A003' },
            },
          ],
        },
      ],
    },
    {
      patient_id: 'patient_02',
      display_name: 'Patient 02',
      variants: [
        {
          variant_id: 'A',
          case_id: 'patient_02_a',
          display_name: 'Versie A',
          questions: [
            {
              id: 'Q02_A_1',
              type: 'choice',
              label: '<p>CTVp_breast_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_2',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVp_breast_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_1', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_3',
              type: 'choice',
              label: '<p>CTVn_L1+L2_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_4',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L1+L2_A&nbsp;onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_3', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_5',
              type: 'choice',
              label: '<p>CTVn_L3+L4_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_6',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L3+L4_A&nbsp;onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_5', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_7',
              type: 'choice',
              label: '<p>CTVn_IMN_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_8',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_IMN_a onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_7', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_9',
              type: 'choice',
              label: '<p>Contra_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_10',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Contra_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_9', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_11',
              type: 'choice',
              label: '<p>Lungs_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_12',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Lungs_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_11', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_13',
              type: 'choice',
              label: '<p>Heart_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_14',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Heart_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_13', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_15',
              type: 'choice',
              label: '<p>Humeralhead_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_16',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Humeralhead_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_15', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_17',
              type: 'choice',
              label: '<p>Thyroid_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_18',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Thyroid_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_17', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_A_19',
              type: 'choice',
              label: '<p>Oesophagus_A</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_A_20',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Oesophagus_A onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_A_19', operator: 'equals', value: 'A003' },
            },
          ],
        },
        {
          variant_id: 'B',
          case_id: 'patient_02_b',
          display_name: 'Versie B',
          questions: [
            {
              id: 'Q02_B_1',
              type: 'choice',
              label: '<p>CTVp_breast_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_2',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVp_breast_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_1', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_3',
              type: 'choice',
              label: '<p>CTVn_L1+L2_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_4',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L1+L2_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_3', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_5',
              type: 'choice',
              label: '<p>CTVn_L3+L4_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_6',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_L3+L4_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_5', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_7',
              type: 'choice',
              label: '<p>CTVn_IMN_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_8',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat CTVn_IMN_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_7', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_9',
              type: 'choice',
              label: '<p>Contra_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_10',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Contra_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_9', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_11',
              type: 'choice',
              label: '<p>Lungs_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_12',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Lungs_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_11', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_13',
              type: 'choice',
              label: '<p>Heart_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_14',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Heart_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_13', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_15',
              type: 'choice',
              label: '<p>Humeralhead_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_16',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Humeralhead_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_15', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_17',
              type: 'choice',
              label: '<p>Thyroid_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_18',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Thyroid_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_17', operator: 'equals', value: 'A003' },
            },
            {
              id: 'Q02_B_19',
              type: 'choice',
              label: '<p>Oesophagus_B</p>',
              required: true,
              choices: [
                { value: 'A001', label: '1. Klinisch bruikbaar: geen correcties nodig.' },
                { value: 'A002', label: '2. Nog niet klinisch bruikbaar, enkele correcties nodig.' },
                { value: 'A003', label: '3. Onbruikbaar: het is beter om opnieuw te starten.' },
              ],
            },
            {
              id: 'Q02_B_20',
              type: 'text',
              label: '<p>Wat is de belangrijkste reden dat Oesophagus_B onbruikbaar is?</p>',
              required: true,
              placeholder: 'Beschrijf de reden... Bijvoorbeeld: Craniaal te groot, te dicht bij het doelgebied, mediaal te klein, etc.',
              show_if: { source_question_id: 'Q02_B_19', operator: 'equals', value: 'A003' },
            },
          ],
        },
      ],
    },
  ],

  turing_cases: [],

  feedback_questions: [
    {
      id: 'additional_feedback',
      type: 'text',
      label: 'Aanvullende opmerkingen of feedback?',
      required: false,
      placeholder: 'Optionele aanvullende feedback...',
    },
  ],
};

export function getQuestionnaireStats() {
  const allVariants = questionnaireConfig.segmentation_patients.flatMap(p => p.variants);
  return {
    totalSegmentationCases: allVariants.length,
    totalQuestions: allVariants.reduce((acc, v) => acc + v.questions.length, 0),
  };
}
